name: OKX → Telegram

on:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes
  workflow_dispatch:        # allow manual run

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch announcements
        id: fetch
        run: |
          curl -s 'https://www.okx.com/api/v5/support/announcements' -o /tmp/okx.json
          NOW=$(date +%s)

          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # Manual run: take the latest announcement only
            jq -r '
              .data[0].details[0]
              | {title: .title, url: .url, pTime: .pTime, annType: .annType}
            ' /tmp/okx.json > /tmp/to_send.json
          else
            # Scheduled run: only announcements within last 5 minutes
            jq --arg now "$NOW" '
              .data[].details[]
              | select(((.pTime | tonumber) / 1000) > ($now|tonumber - 300))
              | {title: .title, url: .url, pTime: .pTime, annType: .annType}
            ' /tmp/okx.json > /tmp/to_send.json
          fi

          cat /tmp/to_send.json

      - name: Send to Telegram
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          if [ -s /tmp/to_send.json ]; then
            jq -c '.' /tmp/to_send.json | while read ann; do
              TITLE=$(echo "$ann" | jq -r '.title')
              URL=$(echo "$ann" | jq -r '.url')
              PUBLISHED=$(echo "$ann" | jq -r '.pTime')
              ANNTYPE=$(echo "$ann" | jq -r '.annType')
              DATE=$(date -d @"$(($PUBLISHED/1000))" "+%Y-%m-%d %H:%M:%S UTC")

              TEXT="📢 *$TITLE*%0A%0A🗂️ Type: \`$ANNTYPE\`%0A🕒 Date: $DATE%0A%0A👉 [Read more]($URL)"

              curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
                -H "Content-Type: application/json" \
                -d "{
                  \"chat_id\": \"${CHAT_ID}\",
                  \"text\": \"${TEXT}\",
                  \"parse_mode\": \"Markdown\",
                  \"disable_web_page_preview\": true
                }"
            done
          else
            echo "No new announcements"
          fi


