name: OKX → Telegram

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch announcements
        run: |
          curl -s 'https://www.okx.com/api/v5/support/announcements' -o /tmp/okx.json
          # Get current timestamp in seconds
          NOW=$(date +%s)
          # Filter announcements published in the last 5 minutes
          jq --arg now "$NOW" '
            .data[]
            | select(((.createTime | tonumber) / 1000) > ($now|tonumber - 300))
            | {title: .title, url: .url, ts: .createTime}
          ' /tmp/okx.json > /tmp/new.json
          cat /tmp/new.json

      - name: Send to Telegram
        if: success()
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          if [ -s /tmp/new.json ]; then
            jq -c '.[]' /tmp/new.json | while read item; do
              TITLE=$(echo "$item" | jq -r '.title')
              URL=$(echo "$item" | jq -r '.url')
              TEXT="$TITLE%0A$URL"
              curl -s "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage?chat_id=${CHAT_ID}&text=${TEXT}"
            done
          else
            echo "No new announcements in the last 5 minutes"
          fi
